name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.1"
      - name: go env
        run: 'echo "GOCACHE=$(go env GOCACHE)" >> "$GITHUB_ENV"'
      - uses: actions/cache/restore@v3
        with:
          path: ${{ env.GOCACHE }}/fuzz
          key: ${{ runner.os }}-GOCACHE-fuzz
      - name: go test
        run: go test -v ./...
      - name: "fuzz: Split()"
        run: go test -v -test.run FuzzSplit -fuzz FuzzSplit -fuzztime 3m .
      - uses: actions/cache/save@v3
        with:
          path: ${{ env.GOCACHE }}/fuzz
          key: ${{ runner.os }}-GOCACHE-fuzz
